## Aplicación de NumPy

-----------------------

#### Ejemplo 1

Los datos contenidos en el fichero [datos.txt](./datos.txt) describe las poblaciones de tres tipos de serpientes en el sur de Africa durante 20 años.

In [3]:
import numpy as np
data = np.loadtxt('./datos.txt')    # carga de los datos
data

array([[  2000.,  30000.,   3000.,  38300.],
       [  2001.,  37200.,   6100.,  48200.],
       [  2002.,  60200.,   9800.,  31600.],
       [  2003.,  77300.,  36200.,  38200.],
       [  2004.,  36300.,  69300.,  30600.],
       [  2005.,  20600.,  31700.,  49800.],
       [  2006.,  18100.,  19000.,  38600.],
       [  2007.,  21300.,  13000.,  32300.],
       [  2008.,  22000.,   8300.,  43600.],
       [  2009.,  26300.,   9100.,  32100.],
       [  2010.,  27100.,   7300.,  36000.],
       [  2011.,  30300.,   8000.,  36800.],
       [  2012.,  67000.,  12300.,  33800.],
       [  2013.,  76600.,  19600.,  30900.],
       [  2014.,  62300.,  36700.,  49300.],
       [  2015.,  19600.,  61100.,  39000.],
       [  2016.,  11200.,  29700.,  36700.],
       [  2017.,   7600.,  16800.,  41800.],
       [  2018.,  13600.,   9700.,  33300.],
       [  2019.,  16200.,  10100.,  31300.],
       [  2020.,  23700.,   8600.,  47300.]])

In [4]:
data.shape #21 filas, 4 columnas

(21, 4)

* Cálculo de la media de población de cada tipo a lo largo del tiempo.


In [ ]:
d = data[:, 1:] #por la profesora

In [ ]:
d.mean(axis = 0) #por la profesora

In [91]:
tipoA = data[:, 1]
np.mean(tipoA)

33547.619047619046

In [92]:
tipoB = data[:, 2]
np.mean(tipoB)

20257.142857142859

In [93]:
tipoC = data[:, 3]
np.mean(tipoC)

38071.428571428572

In [102]:
medias = np.array([np.mean(tipoA), np.mean(tipoB), np.mean(tipoC)])
medias

array([ 33547.61904762,  20257.14285714,  38071.42857143])

* Cálculo de la __desviación estándar__ de la muestra. Se trata de una medida de dispersión para variables. Muestra la agrupación de los datos alrededor de un valor central (la media o promedio).

In [ ]:
d.std(axis = 0) #por la profesora

In [48]:
np.std(tipoA)

21173.559861020269

In [49]:
np.std(tipoB)

17581.932594043712

In [50]:
np.std(tipoC)

6209.9108848097749

In [103]:
stds = np.array([np.std(tipoA), np.std(tipoB), np.std(tipoC)])
stds

array([ 21173.55986102,  17581.93259404,   6209.91088481])

* ¿Qué especie ha tenido más población por año?

In [ ]:
maximo = d.max(axis = 1) #por la profesora

In [ ]:
especie = d.argmax(axis = 1) + 1 #especie 1, especie 2 y especie 3 #por la profesora

In [ ]:
valores = list(zip(especie, maximo)) #por la profesora

In [ ]:
año = data[: , 0] #por la profesora

In [ ]:
d = dict(zip(year, valores)) #por la profesora

In [ ]:
d2 = { int(c) : v for c,v in d.items()} #quitando los decimales de los años, listas por comprension #por la profesora

In [ ]:
d2 = { int(c) : (e, int(m) ) for c, (e,m) in d.items()} #por la profesora

In [135]:
data2 = data[:, (1,2,3)]

In [109]:
maximos = np.max(data2, axis = 1)
maximos

array([ 38300.,  48200.,  60200.,  77300.,  69300.,  49800.,  38600.,
        32300.,  43600.,  32100.,  36000.,  36800.,  67000.,  76600.,
        62300.,  61100.,  36700.,  41800.,  33300.,  31300.,  47300.])

In [126]:
especies = []
for i in maximos:
    if i in tipoA:
        especies.append('Tipo A')
    if i in tipoB:
        especies.append('Tipo B')
    else:
        especies.append('Tipo C')
             
print(especies)

['Tipo C', 'Tipo C', 'Tipo A', 'Tipo C', 'Tipo A', 'Tipo C', 'Tipo B', 'Tipo C', 'Tipo C', 'Tipo C', 'Tipo C', 'Tipo C', 'Tipo C', 'Tipo C', 'Tipo A', 'Tipo C', 'Tipo A', 'Tipo C', 'Tipo A', 'Tipo C', 'Tipo B', 'Tipo B', 'Tipo C', 'Tipo C', 'Tipo C', 'Tipo C']


In [136]:
años = list(range(2000, 2021, 1))

In [133]:
solucion = zip(años, especies)
list(solucion)

[(2000, 'Tipo C'),
 (2001, 'Tipo C'),
 (2002, 'Tipo A'),
 (2003, 'Tipo C'),
 (2004, 'Tipo A'),
 (2005, 'Tipo C'),
 (2006, 'Tipo B'),
 (2007, 'Tipo C'),
 (2008, 'Tipo C'),
 (2009, 'Tipo C'),
 (2010, 'Tipo C'),
 (2011, 'Tipo C'),
 (2012, 'Tipo C'),
 (2013, 'Tipo C'),
 (2014, 'Tipo A'),
 (2015, 'Tipo C'),
 (2016, 'Tipo A'),
 (2017, 'Tipo C'),
 (2018, 'Tipo A'),
 (2019, 'Tipo C'),
 (2020, 'Tipo B')]

------------------------